version: '3.8'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678'
 
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - db
    # expose:
    #   - "3306"
    
      
  node-red:
    image: nodered/node-red:latest
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
      - db 
    volumes:
      - node-red-data:/data
 

  phpmyadmin:
      # depends_on:
      #  - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      networks:
       - db
      # environment:
      #   PMA_HOST: db
   
networks:
  node-red-net:  
  db:  
  

# Names our volume
volumes:
  my-db:
  node-red-data:
  # portainer_data: 
